### ISSUE TITLE
Add API documentation?

### ISSUE THREAD

**Issue by astrojuanlu** [athulpg007/AMAT#4]
The documentation contains a lot of comprehensive examples, that's awesome! 🚀 

I wonder if you would consider adding an API reference as well, using [autodoc](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html), [autosummary](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html), or [sphinx-autoapi](https://pypi.org/project/sphinx-autoapi/)?

**Comment by athulpg007** [comment]
Added an [API Reference](https://amat.readthedocs.io/en/master/api_reference.html) section to docs.  I was not entirely sure to make it more concise looking. I can make further changes if needed.

**Comment by astrojuanlu** [comment]
Perfect! Closing
