### ISSUE TITLE
Clean-up dependencies

### ISSUE THREAD

**Issue by helgee** [athulpg007/AMAT#5]
CC: @astrojuanlu

Since `pandas` and `jupyterlab` are only needed for running the examples and not called from inside the AMAT package, they should not be hard dependencies. Especially installing JupyterLab is a bit excessive.

I would recommend to remove them from [setup.py](https://github.com/athulpg007/AMAT/blob/master/setup.py#L16) and rather instruct users to install them manually if they want to run example notebooks.

I also noticed that `setup.py` and `requirements.txt` are out-of-sync. But I must confess that my Python dependencies management knowledge is a bit rusty and I am not sure what the best practice here is.

**Comment by athulpg007** [comment]
Removed pandas and jupyterlab from setup.py. Added a note in installation instructions telling users to install them manually to run the example notebooks.

The requirements.txt was made for readthedocs build. I am not sure of what the best practice is. I know the rtd build works only with some frozen package versions in the requirements.txt.

**Comment by helgee** [comment]
> The requirements.txt was made for readthedocs build. I am not sure of what the best practice is. I know the rtd build works only with some frozen package versions in the requirements.txt.

@astrojuanlu Can you comment on this?

**Comment by athulpg007** [comment]
While I wait for the reply, I will look at some other repositories and the readthedocs docs on how to do this in a cleaner way.

**Comment by athulpg007** [comment]
Moved the requirements file to docs/requirements.txt with dependencies for both the package and docs now listed in a single file.

**Comment by astrojuanlu** [comment]
Having a `docs/requirements.txt` with the documentation-related dependencies is [the recommended solution](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html). This can be closed 👍🏽
